name: Pads AUR Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deps
      run: sudo apt-get update && sudo apt-get install libpulse-dev
    - name: Setup
      run: cargo install cargo-aur
    - name: Build
      run: cargo aur